services:
  postgres:
    image: postgres:14-alpine
    container_name: pm-postgres
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: projectmgmt
    volumes:
      - pm_postgres_data:/var/lib/postgresql/data
volumes:
  pm_postgres_data:
